[template]
rename = [
  { from="converter.smithy", to="{{to_snake_case interface}}.smithy" },
]

[[placeholders]]
name = "interface"
type = "string"
prompt = "Interface name (a short identifier such as 'messaging' or 'search')?"
default = "converter"
regex = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[placeholders]]
name = "namespace"
type = "string"
prompt = "Namespace prefix?"
default = "org.example.interfaces"
regex = "^([a-z][a-z0-9_.]+)$"


